### ISSUE TITLE
New Feature: Hold piece

### ISSUE THREAD

**Issue by fagustin07** [trungk18/angular-tetris#17]
**Describe the feature**
I like play tetris and this project, and I feel that the feature _**hold_piece**_ would be a good contribution to this project for people who play tetris and often use this functionality. Like in [this tetris game](https://tetris.com/play-tetris) .

**Describe the solution you'd like**
I will do some deep research on the project code and work to incorporate this functionality, visually and functionally.

**Additional context**
I know many people who like to play tetris with this functionality (I include myself). 
The result who I expected would be something like this, adapted to this project(visually):

- One place to user know the holded piece:
![hold_piece_1](https://user-images.githubusercontent.com/57112653/139345952-445a359c-2d12-4a32-922f-020501a96ce3.jpg)

- User can hold a piece:
![hold_piece_2](https://user-images.githubusercontent.com/57112653/139346212-959ab79e-6849-4c9d-8e56-5be92769f0a8.jpg)

**Comment by fagustin07** [comment]
@trungk18  Hello! After many hours, I have a draft UI + functionally. What do you think about this UI?

![image](https://user-images.githubusercontent.com/57112653/142512869-ff3f345e-8683-47fe-b522-0d357fc501fb.png)

**Comment by trungk18** [comment]
@fagustin07 I have never used the `Hold` function but it looks to me. Sorry for replying late 🤣 I have been pretty busy lately.
